version: '3'
services:
  master:
    build: ./jenkins-master
    ports:
      - "50000:50000"
    volumes:
        - jenkins-log:/var/log/jenkins
        - jenkins-data:/var/jenkins_home
    networks:
        - jenkins-net
  nginx:
    build: ./jenkins-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - jenkins-net
  certbot:
     image: certbot/certbot
     volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
volumes:
  jenkins-log:
  jenkins-data:
networks:
  jenkins-net: